### ISSUE TITLE
[Bug]: 输入电话号码到验证码这一步出现error

### ISSUE THREAD

**Issue by 13299118606** [tangyoha/telegram_media_downloader#176]
### telegram_media_downloader version or commit

v2.2.0

### What OS are you seeing the problem on?

Windows

### Python Version

3.12.4

### What happened?

A bug happened!

```
Is "+86132****8606" correct? (y/N): y
2024-06-26 11:12:38.079 | ERROR    | __main__:main:640 - Telegram says: [406 Not Acceptable] - [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")
Traceback (most recent call last):

  File "d:\Anaconda3\envs\telegram_downloader\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │         └ <code object <module> at 0x0000020286C9CCB0, file "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.6.0-win32...
           └ <function _run_code at 0x0000020286C25580>
  File "d:\Anaconda3\envs\telegram_downloader\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x0000020286C9CCB0, file "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.6.0-win32...

  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>    cli.main()
    │   └ <function main at 0x000002028945F420>
    └ <module 'debugpy.server.cli' from 'c:\\Users\\Administrator\\.vscode\\extensions\\ms-python.debugpy-2024.6.0-win32-x64\\bundl...

  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
    └ <function run_file at 0x000002028945F1A0>

  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
    │     │        └ 'e:\\BaiduSyncdisk\\python_project\\telegram_downloader\\telegram_media_downloader\\media_downloader.py'
    │     └ <function run_path at 0x000002028909A160>
    └ <module '_pydevd_bundle.pydevd_runpy' from 'c:\\Users\\Administrator\\.vscode\\extensions\\ms-python.debugpy-2024.6.0-win32-x...

  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path        
    return _run_module_code(code, init_globals, run_name,
           │                │     │             └ '__main__'
           │                │     └ None
           │                └ <code object <module> at 0x00000202898870B0, file "e:\BaiduSyncdisk\python_project\telegram_downloader\telegram_media_downloa...
           └ <function _run_module_code at 0x0000020289099DA0>

  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code    _run_code(code, mod_globals, init_globals,
    │         │     │            └ None
    │         │     └ {'__name__': '__main__', '__doc__': 'Downloads media from telegram.', '__package__': '', '__loader__': None, '__spec__': None...
    │         └ <code object <module> at 0x00000202898870B0, file "e:\BaiduSyncdisk\python_project\telegram_downloader\telegram_media_downloa...
    └ <function _run_code at 0x0000020289099940>

  File "c:\Users\Administrator\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code       
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Downloads media from telegram.', '__package__': '', '__loader__': None, '__spec__': None...
         └ <code object <module> at 0x00000202898870B0, file "e:\BaiduSyncdisk\python_project\telegram_downloader\telegram_media_downloa...

  File "e:\BaiduSyncdisk\python_project\telegram_downloader\telegram_media_downloader\media_downloader.py", line 662, in <module>
    main()
    └ <function main at 0x00000202B40EA020>

> File "e:\BaiduSyncdisk\python_project\telegram_downloader\telegram_media_downloader\media_downloader.py", line 624, in main
    app.loop.run_until_complete(start_server(client))
    │   │    │                  │            └ <module.pyrogram_extension.HookClient object at 0x000002028CC16C00>
    │   │    │                  └ <function start_server at 0x00000202B40E9EE0>
    │   │    └ <function BaseEventLoop.run_until_complete at 0x0000020289F33B00>
    │   └ <ProactorEventLoop running=False closed=False debug=False>
    └ <module.app.Application object at 0x00000202B40C8F50>

  File "d:\Anaconda3\envs\telegram_downloader\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           │      └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-1' coro=<start_server() done, defined at e:\BaiduSyncdisk\python_project\telegram_downloader\telegr...

  File "e:\BaiduSyncdisk\python_project\telegram_downloader\telegram_media_downloader\media_downloader.py", line 597, in start_server
    await client.start()
          │      └ <function HookClient.start at 0x00000202B3224CC0>
          └ <module.pyrogram_extension.HookClient object at 0x000002028CC16C00>

  File "e:\BaiduSyncdisk\python_project\telegram_downloader\telegram_media_downloader\module\pyrogram_extension.py", line 1095, in start
    await self.authorize()
          │    └ <function Client.authorize at 0x000002028C6DE340>
          └ <module.pyrogram_extension.HookClient object at 0x000002028CC16C00>

  File "d:\Anaconda3\envs\telegram_downloader\Lib\site-packages\pyrogram\client.py", line 324, in authorize
    sent_code = await self.send_code(self.phone_number)
                      │    │         │    └ '+8613299118606'
                      │    │         └ <module.pyrogram_extension.HookClient object at 0x000002028CC16C00>
                      │    └ <function SendCode.send_code at 0x000002028C750360>
                      └ <module.pyrogram_extension.HookClient object at 0x000002028CC16C00>
  File "d:\Anaconda3\envs\telegram_downloader\Lib\site-packages\pyrogram\methods\auth\send_code.py", line 54, in send_code
    r = await self.invoke(
              │    └ <function Invoke.invoke at 0x000002028C7462A0>
              └ <module.pyrogram_extension.HookClient object at 0x000002028CC16C00>
  File "d:\Anaconda3\envs\telegram_downloader\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
              │    │       └ <function Session.invoke at 0x000002028C437060>
              │    └ <pyrogram.session.session.Session object at 0x00000202B4092840>
              └ <module.pyrogram_extension.HookClient object at 0x000002028CC16C00>
  File "d:\Anaconda3\envs\telegram_downloader\Lib\site-packages\pyrogram\session\session.py", line 358, in invoke
    return await self.send(query, timeout=timeout)
                 │    │    │              └ 15
                 │    │    └ pyrogram.raw.functions.auth.SendCode(phone_number='8613299118606', api_id=26734007, api_hash='27433eb88b42b14cb859ecc04624a62...
                 │    └ <function Session.send at 0x000002028C436FC0>
                 └ <pyrogram.session.session.Session object at 0x00000202B4092840>
  File "d:\Anaconda3\envs\telegram_downloader\Lib\site-packages\pyrogram\session\session.py", line 328, in send
    RPCError.raise_it(result, type(data))
    │        │        │            └ pyrogram.raw.functions.auth.SendCode(phone_number='8613299118606', api_id=26734007, api_hash='27433eb88b42b14cb859ecc04624a62...
    │        │        └ pyrogram.raw.types.RpcError(error_code=406, error_message='UPDATE_APP_TO_LOGIN')
    │        └ <staticmethod(<function RPCError.raise_it at 0x000002028C2EE520>)>
    └ <class 'pyrogram.errors.rpc_error.RPCError'>
  File "d:\Anaconda3\envs\telegram_downloader\Lib\site-packages\pyrogram\errors\rpc_error.py", line 80, in raise_it
    raise getattr(

pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: Telegram says: [406 Not Acceptable] - [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")
```

### Expected Behavior

手机号我用***替代，实际上用的是真实手机号

### Current Behavior

每次输入号码  和确定号码后，就会弹出如此bug

**Comment by usernamelessss** [comment]
俺也一样

**Comment by wtsai92** [comment]
同样报错 Telegram says: [406 Not Acceptable] - [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")

**Comment by Teomit** [comment]
This worked for me:
`pip install pyrogram --upgrade`

**Comment by 13299118606** [comment]
> This worked for me: `pip install pyrogram --upgrade`

Thank you, it really works

**Comment by Charleshzh** [comment]
> > This worked for me: `pip install pyrogram --upgrade`
> 
> Thank you, it really works

may i ask your version of pyrogram

**Comment by Teomit** [comment]
> may i ask your version of pyrogram

telegram_media_downloader uses 2.0.69. Latest version (after upgrade) is 2.0.106

**Comment by 13299118606** [comment]
Pyrogram-2.0.64 (error)  => pyrogram-2.0.106 (pass)

**Comment by 13299118606** [comment]
> > may i ask your version of pyrogram
> > telegram_media_downloader uses 2.0.69. Latest version (after upgrade) is 2.0.106

Pyrogram-2.0.64 (error)  => pyrogram-2.0.106 (pass)

**Comment by 13299118606** [comment]
> > > This worked for me: `pip install pyrogram --upgrade`
> > 
> > 
> > Thank you, it really works
> 
> may i ask your version of pyrogram

Pyrogram-2.0.64 (error)  => pyrogram-2.0.106 (pass)

**Comment by Romntic** [comment]
pyrogram-2.0.106     not  working with me on Pyrogram (version 2.0.106)  at  Telegram Media Downloader 2.2.3

**Comment by yikolemon** [comment]
最新release的exe版本无法使用，源码编译升级后可以使用，请问有人知道如何通过exe版本升级依赖使用吗。编译软件需要C++支持有些麻烦。

**Comment by xinmans** [comment]
docker版本亲测有效
