### ISSUE TITLE
[Bug]: Invalid chat link  Telegram says: [400 MEDIA_EMPTY] - The media you tried to send is invalid (caused by "messages.SendMultiMedia")

### ISSUE THREAD

**Issue by wzgrx** [tangyoha/telegram_media_downloader#177]
### telegram_media_downloader version or commit

最新

### What OS are you seeing the problem on?

Windows

### What happened?

A bug happened!转发一直显示Invalid chat link

pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] - The message id is invalid (caused by "messages.ForwardMessages")
2024-06-27 13:21:51.384 | ERROR    | module.pyrogram_extension:upload_telegram_chat_message:305 - Upload file None error: Telegram says: [400 MEDIA_EMPTY] - The media you tried to send is invalid (caused by "messages.SendMultiMedia")
Traceback (most recent call last):

  File "media_downloader.py", line 662, in <module>

  File "media_downloader.py", line 636, in main

  File "media_downloader.py", line 590, in _exec_loop

  File "asyncio\base_events.py", line 640, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run

  File "pyrogram\dispatcher.py", line 240, in handler_worker

  File "module\bot.py", line 833, in forward_messages

  File "module\bot.py", line 877, in forward_normal_content

> File "module\pyrogram_extension.py", line 295, in upload_telegram_chat_message

  File "module\pyrogram_extension.py", line 450, in _upload_telegram_chat_message

  File "module\pyrogram_extension.py", line 532, in forward_multi_media

  File "module\pyrogram_extension.py", line 568, in proc_cache_forward

  File "module\send_media_group_v2.py", line 389, in send_media_group_v2

  File "pyrogram\methods\advanced\invoke.py", line 79, in invoke

  File "pyrogram\session\session.py", line 358, in invoke

  File "pyrogram\session\session.py", line 328, in send

  File "pyrogram\errors\rpc_error.py", line 91, in raise_it

pyrogram.errors.exceptions.bad_request_400.MediaEmpty: Telegram says: [400 MEDIA_EMPTY] - The media you tried to send is invalid (caused by "messages.SendMultiMedia")
### Expected Behavior

正常

### Current Behavior

正常

**Comment by wzgrx** [comment]
https://github.com/KurimuzonAkuma/pyrogram/issues/53
