### ISSUE TITLE
[Bug]: KeyError: 'tag_name'

### ISSUE THREAD

**Issue by biubiushaka** [tangyoha/telegram_media_downloader#189]
### telegram_media_downloader version or commit

v2.2.4

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

使用的容器镜像为 tangyoha/telegram_media_downloader:latest
初次使用docker start -i启动容器后正常下载了很多资源，后来发现容器不停重启，停止容器再次使用docker start -i发现KeyError: 'tag_name'  的提示，然后容器就应该又自动重启了。

### Expected Behavior

不清楚这是否正常

### Current Behavior

canfig.yaml配置如下：
`api_hash: XXXXXXXXXXXXXXXXXX
api_id: XXXXXX
chat:
- chat_id: me
  last_read_message_id: 831           //此处初始配置为0，未做人为修改
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
# in linux please use /
# save_path: E:\github\telegram_media_downloader
save_path: /app/downloads
proxy:
  scheme: socks5
  hostname: 192.168.X.X
  port: XXXX
language: EN`

### Relevant log output

```shell
docker start -i结果如下（截取了停止回显时的片段）：
2024-08-09 07:40:02.901 | INFO     | __main__:download_media:409 - id=801 /app/downloads/me/2024_08/801 - video_2024-07-08_13-18-38_7390730416732241952.mp4 already download,download skipped.

2024-08-09 07:40:03.138 | INFO     | __main__:main:678 - Stopped!
Traceback (most recent call last):
  File "/app/media_downloader.py", line 692, in <module>
    main()
  File "/app/media_downloader.py", line 679, in main
    check_for_updates(app.proxy)
  File "/app/utils/updates.py", line 70, in check_for_updates
    latest_release = get_latest_release(proxy_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils/updates.py", line 58, in get_latest_release
    if f"v{__version__}" != latest_release["tag_name"]:
                            ~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'tag_name'
```

**Comment by devhub126** [comment]
同上

**Comment by opisreal** [comment]
可能环境有问题，我这终端启用报相同错误，用pycharm创建新的python虚拟环境跑起来没问题。

**Comment by huaiyi255** [comment]
同样报错
Traceback (most recent call last):
  File "media_downloader.py", line 692, in <module>
  File "media_downloader.py", line 679, in main
  File "utils\updates.py", line 70, in check_for_updates
  File "utils\updates.py", line 58, in get_latest_release
KeyError: 'tag_name'
[7136] Failed to execute script 'media_downloader' due to unhandled exception!
