### ISSUE TITLE
[Bug]: 下载200个左右就开始报错了

### ISSUE THREAD

**Issue by ranlabs** [tangyoha/telegram_media_downloader#190]
### telegram_media_downloader version or commit

2.2.4

### What OS are you seeing the problem on?

Mac

### Python Version

3.8.19

### What happened?

A bug happened!2024-08-15 13:21:57.977 | WARNING  | __main__:_check_download_finish:74 - Media downloaded with wrong size: 208666624, actual: 1310459263, file name: 
2024-08-15 13:21:57.985 | WARNING  | __main__:download_media:453 - Message[867]: file reference expired, refetching...
[13:22:01] ERROR    Request timed out                                                                                                                                                client.py:1086
                    Traceback (most recent call last):
                      File "/Users/pangge/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pyrogram/client.py", line 990, in get_file
                        r = await session.invoke(
                      File "/Users/pangge/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pyrogram/session/session.py", line 424, in invoke
                        return await self.invoke(query, retries - 1, timeout)
                      File "/Users/pangge/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pyrogram/session/session.py", line 424, in invoke
                        return await self.invoke(query, retries - 1, timeout)
                      File "/Users/pangge/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pyrogram/session/session.py", line 424, in invoke
                        return await self.invoke(query, retries - 1, timeout)
                      [Previous line repeated 7 more times]
                      File "/Users/pangge/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pyrogram/session/session.py", line 414, in invoke
                        raise e from None
                      File "/Users/pangge/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pyrogram/session/session.py", line 401, in invoke
                        return await self.send(query, timeout=timeout)
                      File "/Users/pangge/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pyrogram/session/session.py", line 363, in send
                        raise TimeoutError("Request timed out")
                    TimeoutError: Request timed out

### Expected Behavior

能一直持续下载

### Current Behavior

下载连续报错

**Comment by ranlabs** [comment]
是不是TG api有用量限制，这个问题观察很久，每天只能下载一定数量，然后就开始报错，第二天重试就可以，然后继续下载一定数量就开始报错。

**Comment by lancer-wang** [comment]
降到2.2.3 有效，不过我现在不知道为什么降不了了

**Comment by tangyoha** [comment]
> 降到2.2.3 有效，不过我现在不知道为什么降不了了

可能是pyrogram库还是有问题，过几天想办法回滚下

**Comment by lancer-wang** [comment]
> > 降到2.2.3 有效，不过我现在不知道为什么降不了了
> 
> 可能是pyrogram库还是有问题，过几天想办法回滚下

使用2.2.3报这个
![image](https://github.com/user-attachments/assets/815021b5-0197-44c9-a9f5-c7fc5708b765)

**Comment by lancer-wang** [comment]
Original error was: Error loading shared library libopenblas.so.3: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-aarch64-linux-musl.so)

**Comment by zhao-heng-sheng** [comment]
我遇到情况是到190个左右就会自动停掉，删除掉data.yaml文件里的内容后再次运行就正常了。
