### ISSUE TITLE
[Bug]:  报错Failed to execute script 'media_downloader' due to unhandled exception!

### ISSUE THREAD

**Issue by huaiyi255** [tangyoha/telegram_media_downloader#214]
### telegram_media_downloader version or commit

2.2.4

### What OS are you seeing the problem on?

Windows

### Python Version

3.11

### What happened?

下载一小会就报错

### Expected Behavior

下载一小会就报错

### Current Behavior

11

### Relevant log output

```shell
2024-12-20 09:32:53.870 | INFO     | __main__:main:678 - Stopped!
Traceback (most recent call last):
  File "media_downloader.py", line 692, in <module>
  File "media_downloader.py", line 679, in main
  File "utils\updates.py", line 70, in check_for_updates
  File "utils\updates.py", line 58, in get_latest_release
KeyError: 'tag_name'
[7412] Failed to execute script 'media_downloader' due to unhandled exception!
```

**Comment by tangyoha** [comment]
@huaiyi255 hi, This error is caused by an error in obtaining the GitHub release, which we will fix later.
