### ISSUE TITLE
Docker镜像权限问题

### ISSUE THREAD

**Issue by shoaky009** [tangyoha/telegram_media_downloader#43]
增加支持设置UID和GIU，现在镜像版本因权限问题无法启动。

`
2023-04-07 04:38:45.228711+00:00WARNING: Couldn't open 'parser.out'. [Errno 13] Permission denied: '/app/module/parser.out'
2023-04-07 04:38:45.229311+00:00Generating LALR tables
2023-04-07 04:38:45.244312+00:00WARNING: Couldn't create 'module.parsetab'. [Errno 13] Permission denied: '/app/module/parsetab.py'
2023-04-07 04:38:45.420055+00:00WARNING: Couldn't open 'parser.out'. [Errno 13] Permission denied: '/app/module/parser.out'
2023-04-07 04:38:45.420658+00:00Generating LALR tables
2023-04-07 04:38:45.435707+00:00WARNING: Couldn't create 'module.parsetab'. [Errno 13] Permission denied: '/app/module/parsetab.py'
2023-04-07 04:38:45.437448+00:00Traceback (most recent call last):
2023-04-07 04:38:45.437498+00:00File "/app/media_downloader.py", line 43, in <module>
2023-04-07 04:38:45.437533+00:00logger.add(
2023-04-07 04:38:45.437549+00:00File "/usr/local/lib/python3.11/site-packages/loguru/_logger.py", line 762, in add
2023-04-07 04:38:45.437670+00:00wrapped_sink = FileSink(path, **kwargs)
2023-04-07 04:38:45.437719+00:00^^^^^^^^^^^^^^^^^^^^^^^^
2023-04-07 04:38:45.437752+00:00File "/usr/local/lib/python3.11/site-packages/loguru/_file_sink.py", line 166, in __init__
2023-04-07 04:38:45.437772+00:00self._initialize_file()
2023-04-07 04:38:45.437785+00:00File "/usr/local/lib/python3.11/site-packages/loguru/_file_sink.py", line 185, in _initialize_file
2023-04-07 04:38:45.437830+00:00path = self._prepare_new_path()
2023-04-07 04:38:45.437868+00:00^^^^^^^^^^^^^^^^^^^^^^^^
2023-04-07 04:38:45.437883+00:00File "/usr/local/lib/python3.11/site-packages/loguru/_file_sink.py", line 181, in _prepare_new_path
2023-04-07 04:38:45.437906+00:00os.makedirs(dirname, exist_ok=True)
2023-04-07 04:38:45.437934+00:00File "<frozen os>", line 225, in makedirs
2023-04-07 04:38:45.437960+00:00PermissionError: [Errno 13] Permission denied: '/app/log'
`

**Comment by tangyoha** [comment]
为啥出现这个问题，是如何复现该问题的

**Comment by shoaky009** [comment]
> 为啥出现这个问题，是如何复现该问题的

给容器设置了自定义的UID和GID 以下为deployment中securityContext的配置
```yaml
securityContext:
  privileged: false
  runAsGroup: 1000
  runAsUser: 1000
```
