### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by xlch88** [tangyoha/telegram_media_downloader#89]
### telegram_media_downloader version or commit

v2.1.9

### What OS are you seeing the problem on?

Windows

### Python Version

3.11.4

### What happened?

```
telegram_media_downloader>py media_downloader.py
[18:05:11] Telegram Media Downloader v2.1.9,                                                                  meta.py:18           Copyright (C) 2023 tangyoha <https://github.com/tangyoha>
           Licensed under the terms of the MIT License                                                        meta.py:21
2023-06-22 18:05:11.800 | INFO     | utils.meta:print_meta:22 - Device: CPython 3.11.4 - Telegram Media Downloader 2.1.92023-06-22 18:05:11.800 | INFO     | utils.meta:print_meta:23 - System: Windows 10 (EN)
 * Serving Flask app 'module.web'
 * Debug mode: off
2023-06-22 18:05:13.914 | SUCCESS  | __main__:main:592 - Successfully started (Press Ctrl+C to stop)
2023-06-22 18:05:13.914 | INFO     | __main__:download_chat_task:508 - Downloading files failed during last run...
2023-06-22 18:05:14.219 | ERROR    | __main__:worker:491 - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):

  File "telegram_media_downloader\media_downloader.py", line 629, in <module>
    main()
    └ <function main at 0x00000276898CBE20>

  File "telegram_media_downloader\media_downloader.py", line 603, in main
    _exec_loop()
    └ <function _exec_loop at 0x00000276898CBD80>

  File "telegram_media_downloader\media_downloader.py", line 570, in _exec_loop
    app.loop.run_until_complete(run_until_all_task_finish())
    │   │    │                  └ <function run_until_all_task_finish at 0x00000276898CBCE0>
    │   │    └ <function BaseEventLoop.run_until_complete at 0x00000276862A9080>
    │   └ <ProactorEventLoop running=True closed=False debug=False>
    └ <module.app.Application object at 0x0000027689850CD0>

  File "E:\runtime\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002768635C360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "E:\runtime\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "E:\runtime\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000276862AADE0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "E:\runtime\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000027685DE1440>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "E:\runtime\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

> File "telegram_media_downloader\media_downloader.py", line 489, in worker
    await download_task(client, message, node)
          │             │       │        └ <module.app.TaskNode object at 0x0000027687C7ED90>
          │             │       └ pyrogram.types.Message(id=1245, empty=True)
          │             └ <pyrogram.client.Client object at 0x00000276898FB850>
          └ <function download_task at 0x00000276898CB7E0>

  File "telegram_media_downloader\media_downloader.py", line 273, in download_task
    download_status, file_name = await download_media(
                                       └ <function download_media at 0x00000276898CB920>

  File "telegram_media_downloader\module\pyrogram_extension.py", line 337, in inner
    status, file_name = await func(
                              └ <function download_media at 0x00000276898CB880>

  File "telegram_media_downloader\media_downloader.py", line 359, in download_media
    message = await fetch_message(client, message)
                    │             │       └ pyrogram.types.Message(id=1245, empty=True)
                    │             └ <pyrogram.client.Client object at 0x00000276898FB850>
                    └ <function fetch_message at 0x0000027689286660>

  File "telegram_media_downloader\module\pyrogram_extension.py", line 500, in fetch_message
    chat_id=message.chat.id,
            │       └ None
            └ pyrogram.types.Message(id=1245, empty=True)

AttributeError: 'NoneType' object has no attribute 'id'






```

### Expected Behavior

After the download is complete, open it again and the above error will appear

### Current Behavior

After the download is complete, open it again and the above error will appear

**Comment by xlch88** [comment]
commit d0d576f98f0bb900525330b5e83f2044748a2df1

**Comment by tangyoha** [comment]
#88
