### ISSUE TITLE
[Bug]: TimeoutError

### ISSUE THREAD

**Issue by 40OIL** [tangyoha/telegram_media_downloader#91]
### telegram_media_downloader version or commit

2.1.9

### What OS are you seeing the problem on?

Windows

### Python Version

3.8.10

### What happened?

Yesterday I ran into a problem. On neighboring computers - in one your program works, and in the other it ends with a timeout. A day ago, both there and there worked fine. Works on win7, stops on win10. Everything else is the same - settings, session, provider, telegram_media_downloader version, Python version, etc.
Proxies and VPNs don't help. Moreover, Telegram Desktop works both there and there, I don’t use ProxyMTProto.
On win10, only Chrome, Opera, TeamViewer and Microsoft Defender Antivirus (KB2267602) was updated yesterday.
Folders \Python38\Lib\site-packages\pyrogram and \telegram_media_downloader added to Defender exceptions - does not help.
I tried to delete media_downloader.session and start a new session - the program only asks for the Telegram login code, it does not ask for a cloud password - it exits by timeout.

Windows 10 Enterprise LTSC Edition
Version 21H2
OS Build 19044.3086
Interoperability Windows Feature Experience Pack 1000.19041.1000.0

git log --oneline
`* 1280550 (HEAD -> master, origin/master, origin/HEAD) fix: download error (#88)`

### Expected Behavior

```
2023-06-29 21:16:09.270 | INFO     | utils.meta:print_meta:22 - Device: CPython 3.8.10 - Telegram Media Downloader 2.1.9
2023-06-29 21:16:09.271 | INFO     | utils.meta:print_meta:23 - System: Windows 10 (EN)
2023-06-29 21:18:42.708 | ERROR    | __main__:main:610 - 
Traceback (most recent call last):

  File "media_downloader.py", line 632, in <module>
    main()
    L <function main at 0x0000023646561C10>

> File "media_downloader.py", line 594, in main
    client.start()
    │      L <function Start.start at 0x0000023644921CA0>
    L <pyrogram.client.Client object at 0x0000023646572CA0>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           │    │                  L <coroutine object Start.start at 0x0000023646558E40>
           │    L <function BaseEventLoop.run_until_complete at 0x0000023642989C10>
           L <ProactorEventLoop running=False closed=False debug=False>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
           │      L <method 'result' of '_asyncio.Task' objects>
           L <Task finished name='Task-1' coro=<Start.start() done, defined at C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\s...

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\utilities\start.py", line 62, in start
    await self.authorize()
          │    L <function Client.authorize at 0x00000236448B64C0>
          L <pyrogram.client.Client object at 0x0000023646572CA0>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\client.py", line 346, in authorize
    signed_in = await self.sign_in(self.phone_number, sent_code.phone_code_hash, self.phone_code)
                      │    │       │    │             │         │                │    L '26729'
                      │    │       │    │             │         │                L <pyrogram.client.Client object at 0x0000023646572CA0>
                      │    │       │    │             │         L '1c8crgrd22267439ff'
                      │    │       │    │             L pyrogram.types.SentCode(type=pyrogram.enums.SentCodeType.APP, phone_code_hash='1c8crgrd22267439ff')
                      │    │       │    L '+79121112233'
                      │    │       L <pyrogram.client.Client object at 0x0000023646572CA0>
                      │    L <function SignIn.sign_in at 0x0000023644921940>
                      L <pyrogram.client.Client object at 0x0000023646572CA0>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\auth\sign_in.py", line 63, in sign_in
    r = await self.invoke(
              │    L <function Invoke.invoke at 0x00000236449164C0>
              L <pyrogram.client.Client object at 0x0000023646572CA0>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
              │    │       L <function Session.invoke at 0x00000236444D33A0>
              │    L <pyrogram.session.session.Session object at 0x00000236465ABA90>
              L <pyrogram.client.Client object at 0x0000023646572CA0>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 378, in invoke
    return await self.invoke(query, retries - 1, timeout)
                 │    │      │      │            L 15
                 │    │      │      L 5
                 │    │      L pyrogram.raw.functions.auth.SignIn(phone_number='79121112233', phone_code_hash='1c8crgrd22267439ff', phone_code='26729')
                 │    L <function Session.invoke at 0x00000236444D33A0>
                 L <pyrogram.session.session.Session object at 0x00000236465ABA90>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 378, in invoke
    return await self.invoke(query, retries - 1, timeout)
                 │    │      │      │            L 15
                 │    │      │      L 4
                 │    │      L pyrogram.raw.functions.auth.SignIn(phone_number='79121112233', phone_code_hash='1c8crgrd22267439ff', phone_code='26729')
                 │    L <function Session.invoke at 0x00000236444D33A0>
                 L <pyrogram.session.session.Session object at 0x00000236465ABA90>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 378, in invoke
    return await self.invoke(query, retries - 1, timeout)
                 │    │      │      │            L 15
                 │    │      │      L 3
                 │    │      L pyrogram.raw.functions.auth.SignIn(phone_number='79121112233', phone_code_hash='1c8crgrd22267439ff', phone_code='26729')
                 │    L <function Session.invoke at 0x00000236444D33A0>
                 L <pyrogram.session.session.Session object at 0x00000236465ABA90>
  [Previous line repeated 2 more times]

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 371, in invoke
    raise e from None

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 358, in invoke
    return await self.send(query, timeout=timeout)
                 │    │    │              L 15
                 │    │    L pyrogram.raw.functions.auth.SignIn(phone_number='79121112233', phone_code_hash='1c8crgrd22267439ff', phone_code='26729')
                 │    L <function Session.send at 0x00000236444D3310>
                 L <pyrogram.session.session.Session object at 0x00000236465ABA90>

  File "C:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 323, in send
    raise TimeoutError

TimeoutError

```

### Current Behavior

A bug happened!

**Comment by tangyoha** [comment]
@40OIL hi, from the logs you gave, I can't determine what is causing the problem

**Comment by 40OIL** [comment]
I don't understand what's going on either. what other logs to look for to find out more precisely?

**Comment by tangyoha** [comment]
Try a few more times, it looks like a network issue

**Comment by 40OIL** [comment]
A similar problem at the same time manifested itself with github.com/iyear/tdl - there the author advised me to synchronize local time. And indeed, I suddenly discovered that the time was not synchronized for 3 weeks. After synchronization, everything worked!
You can close the issue.
